### ISSUE TITLE
Stata 17, GUI: the container is lacking two libraries

### ISSUE THREAD

**Issue by reisportela** [AEADataEditor/docker-stata#13]
Inside the Singularity container, when calling `xstata-mp`, or `xstata`, I get the message that the container is missing two libraries: libgthread-2.0 and libgtk-x11-2.0.

These are the steps two replicate the issue:

Pull the container

```{bash}
singularity pull --force --arch amd64 library://larsvilhuber/dataeditors/stata17:2022-01-17
```
Run `xstata-mp`

```{bash}
VERSION=17
TAG=2022-01-17
MYHUBID=dataeditors
MYIMG=stata${VERSION}
SYLABSID=larsvilhuber
STATALIC="$(pwd)/stata.lic.${VERSION}"
singularity exec  \
  -B ${STATALIC}:/usr/local/stata/stata.lic \
  -B $(pwd)/code:/code \
  -B $(pwd)/data:/data \
  -B $(pwd)/results:/results \
  -H $(pwd) \
  stata17_2022-01-17.sif xstata-mp
```

From the original script, I changed the version to `2022-01-17` (I was not able to find version `2022-10-12`), added `STATALIC="$(pwd)/stata.lic.${VERSION}"`, replaced `run` with `exec` and added `xstata-mp`.

**Comment by larsvilhuber** [comment]
Sorry, only saw this now. The Docker images (and the derived singularity images) are not meant for the use of Xstata, that that is definitely possible. I'm hesitant to add these additional libraries. My suggestion would be use the posted images as the basis for adding in those libraries (in Docker notation, using `FROM dataeditors/stata${VERSION}:${TAG}` and then installing those libraries (see https://github.com/AEADataEditor/docker-stata/blob/9c00c02b2a600b784ef974d2bb3c08f07217d10a/Dockerfile#L15 )
