### ISSUE TITLE
The entrypoint for the singularity doesn't seem to work

### ISSUE THREAD

**Issue by JContro** [AEADataEditor/docker-stata#14]
Hi! 

I am working on an HPC and I am using the singularity stata17_2022-01-17.sif . I can bind the stata license and code/data/results folders and run stata interactively, but when I add -b program.do (where program.do is in my code directory that I have binded) the singularity doesn't run the program. It doesn't open up stata interactively, but it just runs the container without errors, only it doesn't run the .do file I specified. In fact, if I just put -b anyPprogram.do, it also doens't complain. 

There doesn't seem to be any documentation on how to proceed on this, would you be able to assist?

**Comment by larsvilhuber** [comment]
Hi @JContro 

I just run

```
singularity run -B ${STATALIC}:/usr/local/stata/stata.lic -B $(pwd):/project -H /project ./stata17.sif -b setup.do 
```

and

```
singularity run -B ${STATALIC}:/usr/local/stata/stata.lic -B $(pwd):/project -H $(pwd) ./stata17.sif -b setup.do 
```

(difference only in the option to `-H`).

And it correctly runs the `setup.do` file, generating the `setup.log` file.

You should provide a reproducible example, with the exact command line. Two possible sources:

- you are not used to running in batch mode, and did not notice the "anyPprogram.log" file that was generated. Stata with `-b` option never generates output to the screen.
- you did not specify the `-H`  option (not sure that it is  needed, but who knows)

Check those things out.

**Comment by JContro** [comment]
Thanks! I have managed to get it working now! You're a legend :)
