### ISSUE TITLE
Stata 18

### ISSUE THREAD

**Issue by albertus82** [AEADataEditor/docker-stata#15]
Hi, Stata 18 was released on April 2023; would it be possible to containerize this new version too?

Thanks a lot.

**Comment by larsvilhuber** [comment]
I just got a license, and have posted the Stata 18 docker image: https://hub.docker.com/r/dataeditors/stata18 Feedback appreciated.

**Comment by albertus82** [comment]
Thank you Lars, it seems to work properly:

```
version 18.0

. about

Stata/MP 18.0 for Unix (Linux 64-bit x86-64)
Revision 30 Aug 2023
Copyright 1985-2023 StataCorp LLC

Total usable memory: 15.40 GB
```
