### ISSUE TITLE
`stata-mp` as `ENTRYPOINT`

### ISSUE THREAD

**Issue by mizuhirosuzuki** [AEADataEditor/docker-stata#17]
Just out of curiosity, is there any reason for setting `stata-mp` as `ENTRYPOINT`?
I'd find it more convenient if the entry point is bash, especially if I want to install python and its packages.
Thank you!

**Comment by larsvilhuber** [comment]
The docker image is meant to be run as-is. You can always override the docker `ENTRYPOINT` or the singularity `exec`  binary on the command line, or build a new project specific image using `FROM dataeditors/stata17:$DATE` and change the `ENTRYPOINT` there. In fact, if you want to install python and packages, you SHOULD build a new image. I suggest using a two-stage build, using `library/python:$VERSION` as a basis, and copying the `usr/local/stata` directory from the Stata image.
