### ISSUE TITLE
Where should I put stata.lic

### ISSUE THREAD

**Issue by sscien** [AEADataEditor/docker-stata#7]
Hi,

I was wondering which folder should I put stata.lic? After I pull the docker, it says cannot find license file stata.lic.

Many thanks,
EJ

**Comment by larsvilhuber** [comment]
If following the instructions in the [README.md](https://github.com/AEADataEditor/docker-stata#using-the-image), you can have a `stata.lic` somewhere in a Dropbox folder, or you can put it into the local working directory (e.g., copy it from your Stata installation to where you downloaded the sample), and set 
```
STATALIC=$(pwd)/stata.lic
```
(should work at the Git bash command line, or Zsh on Mac). You can then run the rest, e.g., [interactive Stata](https://github.com/AEADataEditor/docker-stata#to-enter-interactive-stata)
